[package]
name = "filepicker"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58", features = [
  "Win32_System_Com","Win32_UI_Shell","Win32_Foundation",
  "Win32_UI_Shell_Common","Win32_System_Com_StructuredStorage"
]}
serde = { version = "1", features=["derive"] }
serde_json = "1" 